apiVersion: v2
name: hasura
description: A Helm chart for hasura on plural
type: application
version: 0.1.6
appVersion: "v2.0.9"
dependencies:
  - name: hasura
    version: 1.1.6
    repository: https://charts.platy.plus
